package vistas;

import control.AlumnoData;
import control.InscripcionData;
import control.MateriaData;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import modelo.Alumno;
import modelo.Inscripcion;
import modelo.Materia;

public class RegistroInscripciones extends javax.swing.JInternalFrame {

    MateriaData materiaData;
    AlumnoData alumnoData;
    InscripcionData inscripcionData;
    ArrayList<Alumno> listaAlumnos = new ArrayList<>();
    ArrayList<Materia> listaMaterias = new ArrayList<>();
    Alumno alumno;
    Materia materia;
    boolean alumnoSeleccionado;
    boolean materiaSeleccionada;

    /**
     * Creates new form RegistroInscripciones
     */
    public RegistroInscripciones(AlumnoData alumnoData, MateriaData materiaData, InscripcionData inscripcionData) {
        initComponents();
        limpiarCampos();
        this.alumnoData = alumnoData;
        this.materiaData = materiaData;
        this.inscripcionData = inscripcionData;
        listaAlumnos = (ArrayList) alumnoData.obtenerAlumnos();
        llenarListaAlumnos();
        llenarListaMaterias();
        desactivarControles();
    }

    public void limpiarCampos() {
        txtAlumno.setText("");
        txtMateria.setText("");
    }

    public void llenarListaAlumnos() {
        if (txtAlumno.getText() != "") {
            listaAlumnos = (ArrayList) alumnoData.obtenerAlumnos(txtAlumno.getText());
        } else {
            listaAlumnos = (ArrayList) alumnoData.obtenerAlumnos();
        }

        lstAlumnos.removeAll();

        int largoLista = listaAlumnos.size();
        //    String[] apellidoNombre = new String[largoLista];
        Alumno[] apellidoNombre = new Alumno[largoLista];
        int i = 0;

        for (Alumno alumno : listaAlumnos) {
            if (alumno.isActivo()) {
                apellidoNombre[i] = alumno;
                i++;
            }
        }

        lstAlumnos.setModel(new javax.swing.AbstractListModel<Alumno>() {
            public int getSize() {
                return listaAlumnos.size();
            }

            public Alumno getElementAt(int i) {
                return apellidoNombre[i];
            }
        });

    }

    public void llenarListaMaterias() {
        if (txtMateria.getText() != "") {
            listaMaterias = (ArrayList) materiaData.obtenerMateria(txtMateria.getText());
        } else {
            listaMaterias = (ArrayList) materiaData.obtenerMateria();
        }

        lstMaterias.removeAll();

        int largoLista = listaMaterias.size();
        //    String[] apellidoNombre = new String[largoLista];
        Materia[] nombre = new Materia[largoLista];
        int i = 0;

        for (Materia materia : listaMaterias) {
            if (materia.isActivo()) {
                nombre[i] = materia;
                i++;
            }
        }

        lstMaterias.setModel(new javax.swing.AbstractListModel<Materia>() {
            public int getSize() {
                return listaMaterias.size();
            }

            public Materia getElementAt(int i) {
                return nombre[i];
            }
        });

    }

    public void desactivarControles() {
        btnInscribir.setEnabled(false);
        btnDesInscribir.setEnabled(false);
    }

    public void activarControles() {
        btnInscribir.setEnabled(true);
        btnDesInscribir.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAltaInsc = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstMaterias = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstAlumnos = new javax.swing.JList<>();
        btnDesInscribir = new javax.swing.JButton();
        btnInscribir = new javax.swing.JButton();
        txtAlumno = new javax.swing.JTextField();
        txtMateria = new javax.swing.JTextField();
        btnSalir = new javax.swing.JButton();

        setClosable(true);
        setTitle("Alta de inscripción");

        panelAltaInsc.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("INSCRIPCION A MATERIAS");

        jLabel8.setFont(new java.awt.Font("Myanmar Text", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Alumnos por Nombre/Legajo");

        jLabel7.setFont(new java.awt.Font("Myanmar Text", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Materias por Nombre");

        lstMaterias.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstMateriasValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstMaterias);

        lstAlumnos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstAlumnosValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(lstAlumnos);

        btnDesInscribir.setText("Des-Inscribir");
        btnDesInscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesInscribirActionPerformed(evt);
            }
        });

        btnInscribir.setText("Inscribir");
        btnInscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInscribirActionPerformed(evt);
            }
        });

        txtAlumno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAlumnoKeyReleased(evt);
            }
        });

        txtMateria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMateriaKeyReleased(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAltaInscLayout = new javax.swing.GroupLayout(panelAltaInsc);
        panelAltaInsc.setLayout(panelAltaInscLayout);
        panelAltaInscLayout.setHorizontalGroup(
            panelAltaInscLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAltaInscLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAltaInscLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelAltaInscLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelAltaInscLayout.createSequentialGroup()
                        .addGroup(panelAltaInscLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelAltaInscLayout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                                .addGroup(panelAltaInscLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnInscribir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnDesInscribir, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE))
                                .addGap(59, 59, 59))
                            .addGroup(panelAltaInscLayout.createSequentialGroup()
                                .addGroup(panelAltaInscLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtAlumno)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(panelAltaInscLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(txtMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        panelAltaInscLayout.setVerticalGroup(
            panelAltaInscLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAltaInscLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAltaInscLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelAltaInscLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(panelAltaInscLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelAltaInscLayout.createSequentialGroup()
                        .addComponent(btnInscribir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDesInscribir))
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelAltaInsc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelAltaInsc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAlumnoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAlumnoKeyReleased
        alumnoSeleccionado = false;
        alumno = null;
        desactivarControles();
        llenarListaAlumnos();
    }//GEN-LAST:event_txtAlumnoKeyReleased

    private void txtMateriaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMateriaKeyReleased
        materiaSeleccionada = false;
        materia = null;
        desactivarControles();
        llenarListaMaterias();
    }//GEN-LAST:event_txtMateriaKeyReleased

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void lstAlumnosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstAlumnosValueChanged
        
        try{
        if (!lstAlumnos.isSelectionEmpty()) {
            alumnoSeleccionado = true;
            txtAlumno.setText(lstAlumnos.getSelectedValue().toString());
            alumno = lstAlumnos.getSelectedValue();
            if (materiaSeleccionada) {
                activarControles();
            } else {
                desactivarControles();
            }
        }
         }catch(NullPointerException ex){
           JOptionPane.showMessageDialog(null, "Debe seleccionar un item de la lista.");
                    }

        
    }//GEN-LAST:event_lstAlumnosValueChanged

    private void lstMateriasValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstMateriasValueChanged

        try{
        if (!lstMaterias.isSelectionEmpty()) {
            materiaSeleccionada = true;
            txtMateria.setText(lstMaterias.getSelectedValue().toString());
            materia = lstMaterias.getSelectedValue();
            if (alumnoSeleccionado) {
                activarControles();
            } else {
                desactivarControles();
            }
        }
         }catch(NullPointerException ex){
           JOptionPane.showMessageDialog(null, "Debe seleccionar un item de la lista.");
                    }

    }//GEN-LAST:event_lstMateriasValueChanged

    private void btnInscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInscribirActionPerformed

        Inscripcion inscripcion = new Inscripcion(alumno, materia);

        if (inscripcionData.inscribir(inscripcion)) {
            JOptionPane.showMessageDialog(null, "Inscripcion Registrada correctamente.");
        } else {
            
          inscripcion = inscripcionData.buscarInscripcion(alumno, materia);
            
            if (inscripcion.isActivo()) {
                JOptionPane.showMessageDialog(null, "No se pudo guardar la información. No se puede inscribir el mismo alumno dos veces en la misma Materia.");
            } else {
                if (inscripcionData.reInscribir(alumno, materia)) {
                    JOptionPane.showMessageDialog(null, "Se reinscribió el Alumno en la Materia.");
                } else {
                    JOptionPane.showMessageDialog(null, "No se pudo reinscribir el Alumno en la Materia.");
                }
            }

        }


    }//GEN-LAST:event_btnInscribirActionPerformed

    private void btnDesInscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesInscribirActionPerformed

        Inscripcion inscripcion = new Inscripcion(alumno, materia);

        if (inscripcionData.desInscribir(inscripcion)) {
            JOptionPane.showMessageDialog(null, "Alumno Desinscripto correctamente.");
        }
    }//GEN-LAST:event_btnDesInscribirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDesInscribir;
    private javax.swing.JButton btnInscribir;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<Alumno> lstAlumnos;
    private javax.swing.JList<Materia> lstMaterias;
    private javax.swing.JPanel panelAltaInsc;
    private javax.swing.JTextField txtAlumno;
    private javax.swing.JTextField txtMateria;
    // End of variables declaration//GEN-END:variables

}
